.TH test_script(1)

.Sh NAME
.B userwizzard
- script to create users or back them up

.SH SYNOPSIS

.SH DESCRIPTION
.B userwizzard
For script one the main functions are the following:

.RS
.nf
    - input checking 
    - logging
    - group validation and creation
    - user & directory creation
    - backup checking